dist: trusty
language: python
jobs:
  include:
  - env: MITMPROXY=0.18.1
    python: "2.7"
  - env: MITMPROXY=0.18.1
    python: "3.5"
  - env: MITMPROXY=1.0.0
    python: "3.5.2"
  - env: MITMPROXY=latest
    python: "3.6"
  - env: MITMPROXY=latest
    python: "3.7-dev"
before_install:
- mitmproxy="mitmproxy==$MITMPROXY"
- mitmproxy="${mitmproxy%==latest}"
install:
- if [[ $TRAVIS_PYTHON_VERSION = *-dev ]]; then pip install --upgrade setuptools; fi
- pip install $mitmproxy
- pip install pydiatra pyflakes
- pip install restructuredtext-lint pygments
script:
- mitmdump -s cowproxy.py &
- export http_proxy=http://localhost:8080/
- for i in $(seq 10); do
    if ss -tln 'sport = 8080' | grep -w 8080; then break; fi;
    sleep 1;
  done
- curl --silent --fail --show-error --include http://www.example.org/cow
- pkill -x mitmdump
- python -m pydiatra .
- python -m pyflakes .
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
